---
version: '3'
services:
  lcms-test-bed-connector:
    image: lcms-test-bed-connector
    # depends_on:
    #   - broker
    #   - schema_registry
    environment:
      KAFKA_HOST: broker:9092
      SCHEMA_REGISTRY: http://schema_registry:3502

